services:
  master:
    container_name: ${CLUSTER_NAME}_master
    restart: always
    hostname: ${CLUSTER_NAME}-master-1
    privileged: true
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    image: rancher/k3s:${K3S_VERSION:-latest}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network
      # Ingress controller port 80
      - traefik.http.routers.${CLUSTER_NAME}-ingress-controller-https.tls=true
      - traefik.http.routers.${CLUSTER_NAME}-ingress-controller-https.entrypoints=websecure
      - traefik.http.routers.${CLUSTER_NAME}-ingress-controller-https.rule=HostRegexp(`[a-z-_0-9]+.${CLUSTER_DOMAIN}`)
      - traefik.http.routers.${CLUSTER_NAME}-ingress-controller-https.service=${CLUSTER_NAME}-ingress-controller-loadbalancer
      - traefik.http.services.${CLUSTER_NAME}-ingress-controller-loadbalancer.loadbalancer.server.port=80
      # Kubernetes API Server port 6443
#      - traefik.http.routers.${CLUSTER_NAME}-api-server-https.tls=true
#      - traefik.http.routers.${CLUSTER_NAME}-api-server-https.entrypoints=websecure
#      - traefik.http.routers.${CLUSTER_NAME}-api-server-https.rule=Host(`${CLUSTER_API_SERVER}`)
#      - traefik.http.routers.${CLUSTER_NAME}-api-server-https.service=${CLUSTER_NAME}-api-server-loadbalancer
#      - traefik.http.services.${CLUSTER_NAME}-api-server-loadbalancer.loadbalancer.server.port=6443
#      - traefik.http.services.${CLUSTER_NAME}-api-server-loadbalancer.loadbalancer.server.scheme=https
    command:
      - server
#      - --tls-san
#      - ${CLUSTER_API_SERVER}
#      - --cluster-domain
#      - ${API_SERVER_HOST}
    environment:
      - K3S_TOKEN=${K3S_CLUSTER_SECRET:?err}
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=644
    volumes:
      - k3s-server:/var/lib/rancher/k3s
      # k3s will generate a kubeconfig.yaml in this directory. This volume is mounted
      # on your host, so you can then 'export KUBECONFIG=/somewhere/on/your/host/out/kubeconfig.yaml',
      # in order for your kubectl commands to work.
      # - ./.kubeconfig/k3s:/output
      # This directory is where you put all the (yaml) configuration files of
      # the Kubernetes resources. /var/lib/rancher/k3s/server/manifests/
      - ./.manifests/config/traefik.yaml:/var/lib/rancher/k3s/server/manifests/traefik-config.yaml
      - ./.manifests/tools:/var/manifests
    ports:
      - "6443:6443" # Kubernetes API Server
#      - "80:80"     # Ingress controller port 80
#      - "443:443"   # Ingress controller port 443
    networks:
      - traefik-network
      - internal

  worker:
    container_name: ${CLUSTER_NAME}_worker
    hostname: ${CLUSTER_NAME}-worker-1
    image: rancher/k3s:${K3S_VERSION:-latest}
    restart: always
    command:
      - agent
    privileged: true
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    labels:
      - traefik.enable=false
    links:
      - master
    environment:
      - K3S_URL=https://master:6443
      - K3S_TOKEN=${K3S_CLUSTER_SECRET:?err}
    volumes:
      - k3s-agent:/etc/rancher/node
      # this is where you would place an alternative traefik image (saved as a .tar file with
      # 'docker save'), if you want to use it, instead of the traefik:v3.1 image.
      # - /somewhere/on/your/host/custom-image:/var/lib/rancher/k3s/agent/images
    networks:
      - internal

  k8s:
    container_name: ${PROJECT_NAME}_k8s
    restart: always
    network_mode: host
    build:
      context: .
      args:
        USER: ${NON_ROOT_USER:-devops}
        WORKING_DIR: ${WORKING_DIR:-/var/src}
    volumes:
      - ./.kubeconfig:/home/${NON_ROOT_USER:-devops}/.kube
      - ./.manifests/tools:${WORKING_DIR}

volumes:
  k3s-server:
  k3s-agent:

networks:
  internal:
  traefik-network:
    external: true
